export const ALL_VIDEOGAMES = "ALL_VIDEOGAMES";
export const VIDEOGAME_BY_ID = "GET_VIDEOGAME_DETAIL";
export const VIDEOGAME_BY_NAME= "SEARCH_VIDEOGAMES";
export const FILTER_BY_GENRE = "FILTER_BY_GENRE";
export const FILTER_BY_ORIGIN = "FILTER_BY_SOURCE";
export const ORDER_VIDEOGAMES = "ORDER_VIDEOGAMES";
export const CLEAN_DETAIL = "CLEAN_DETAIL";